"""Prompt模板模块"""
from .core_agent_prompts import (
    CORE_AGENT_SYSTEM_PROMPT,
    DOMAIN_INTENT_ENTITIES_PROMPT,
    RESULT_EVALUATION_PROMPT
)
from .specialized_agent_prompts import (
    SPECIALIZED_AGENT_SYSTEM_PROMPT_TEMPLATE,
    QA_RETRIEVAL_NEXT_STEP_PROMPT,
    CALCULATION_NEXT_STEP_PROMPT,
    REVIEW_CONTRACT_NEXT_STEP_PROMPT
)
from .agent_prompts import (
    AGENT_SYSTEM_PROMPT
)

__all__ = [
    'CORE_AGENT_SYSTEM_PROMPT',
    'DOMAIN_INTENT_ENTITIES_PROMPT',
    'RESULT_EVALUATION_PROMPT',
    'SPECIALIZED_AGENT_SYSTEM_PROMPT_TEMPLATE',
    'QA_RETRIEVAL_NEXT_STEP_PROMPT',
    'CALCULATION_NEXT_STEP_PROMPT',
    'REVIEW_CONTRACT_NEXT_STEP_PROMPT',
    'AGENT_SYSTEM_PROMPT'
]

